services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trip_db
    ports:
      - "5432:5432"
    networks:
      - mynet

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py      
    networks:
      - mynet

networks:
  mynet: